#ifndef KOBRA_RT_MESH_BINDINGS_H_
#define KOBRA_RT_MESH_BINDINGS_H_

const int MESH_BINDING_PIXELS		= 0;
const int MESH_BINDING_VIEWPORT		= 1;
const int MESH_BINDING_VERTICES		= 2;
const int MESH_BINDING_TRIANGLES	= 3;
const int MESH_BINDING_TRANSFORMS	= 4;
const int MESH_BINDING_BVH		= 5;
const int MESH_BINDING_MATERIALS	= 6;

#endif
