#ifndef RASTER_BINDINGS
#define RASTER_BINDINGS

const int RASTER_BINDING_UBO		= 0;

const int RASTER_BINDING_ALBEDO_MAP	= 1;
const int RASTER_BINDING_NORMAL_MAP	= 2;
const int RASTER_BINDING_POINT_LIGHTS	= 3;

const int RASTER_BINDING_SKYBOX		= 4;

#endif
